//! Generated project templates and configuration.

use crate::config::UtoProjectConfig;
use std::path::Path;

const UTO_VERSION: &str = "0.5.0"; // Update this when publishing to crates.io

pub fn project_readme(config: &UtoProjectConfig) -> String {
    format!(
        "# {}\n\nGenerated by `uto init`.\n\nThis is a standalone UTO test project template with CLI-owned execution.\n\n## Quick Start\n\n```sh\n# Run default target\nuto run --project .\n\n# Run explicit target\nuto run --project . --target {} --report-json ./.uto/reports/last-run.json\n\n# Summarize report\nuto report --project .\n\n# Generate HTML report\nuto report --project . --html\n\n# Run template integration tests directly\ncargo test\n```\n\n## Test Style\n\nUse `#[uto_test]` to mark framework tests and keep plain Rust test ergonomics:\n\n```rust\nuse uto_test::uto_test;\n\n#[uto_test(target = \"web\", tags = [\"smoke\", \"generated\"], timeout_ms = 30000)]\n#[tokio::test]\nasync fn web_example() {{\n    // ...\n}}\n```\n\n## Files\n\n- `uto.json`: project config\n- `src/lib.rs`: project library root\n- `tests/web_example.rs`: web example test using `uto-test`\n- `tests/mobile_example.rs`: mobile example test using `uto-test`\n- `.uto/reports/`: structured run reports\n",
        config.project_name, config.default_target
    )
}

/// Generate Cargo.toml with crates.io dependencies (production mode).
pub fn cargo_toml_crates_io(project_name: &str) -> String {
    format!(
        "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\n\n[dependencies]\nuto-test = \"{}\"\nuto-reporter = \"{}\"\nuto-logger = \"{}\"\nuto-core = \"{}\"\ntokio = {{ version = \"1\", features = [\"full\"] }}\nlog = \"0.4\"\nserde_json = \"1\"\nwhich = \"7\"\n\n",
        project_name,
        UTO_VERSION,
        UTO_VERSION,
        UTO_VERSION,
        UTO_VERSION
    )
}

/// Generate Cargo.toml with path dependencies (development mode).
pub fn cargo_toml_path_deps(project_name: &str, uto_root: &Path) -> String {
    format!(
        "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\n\n[dependencies]\nuto-test = {{ path = \"{}\" }}\nuto-reporter = {{ path = \"{}\" }}\nuto-logger = {{ path = \"{}\" }}\nuto-core = {{ path = \"{}\" }}\ntokio = {{ version = \"1\", features = [\"full\"] }}\nlog = \"0.4\"\nserde_json = \"1\"\nwhich = \"7\"\n\n",
        project_name,
        uto_root.join("uto-test").display(),
        uto_root.join("uto-reporter").display(),
        uto_root.join("uto-logger").display(),
        uto_root.join("uto-core").display()
    )
}

pub fn project_lib_rs() -> String {
    "//! Generated UTO test project library root.\n".to_string()
}

pub fn web_test_example() -> String {
    r##"use uto_test::uto_test;

#[uto_test(target = "web", tags = ["smoke", "generated"], timeout_ms = 30000)]
#[tokio::test]
async fn web_example_navigates_example_dot_com_or_skips() {
    let session = match uto_test::startNewSession("chrome").await {
        Ok(session) => session,
        Err(_) => {
            println!("Skipping web example: web session could not be created");
            return;
        }
    };

    session.goto("https://example.com").await.expect("goto");
    let title = session.title().await.expect("title");
    assert!(!title.is_empty());

    session.close().await.expect("close");
}
"##
    .to_string()
}

pub fn mobile_test_example() -> String {
    r##"use uto_test::uto_test;

#[uto_test(target = "mobile", tags = ["mobile", "generated"], timeout = 45000)]
#[tokio::test]
async fn mobile_example_creates_session_or_skips() {
    let session = match uto_test::startNewSessionWithArg("android", 16).await {
        Ok(session) => session,
        Err(err) => {
            println!("Skipping mobile example: mobile session could not be created: {err}");
            return;
        }
    };

    session.close().await.expect("close mobile session");
}
"##
    .to_string()
}
