//! Generated project templates and configuration.

use crate::config::UtoProjectConfig;
use std::path::Path;

pub fn project_readme(config: &UtoProjectConfig) -> String {
    format!(
        "# {}\n\nGenerated by `uto init`.\n\nThis is a standalone UTO test project template with example tests and a local runner.\n\n## Quick Start\n\n```sh\n# Run default target\nuto run --project .\n\n# Run explicit target\nuto run --project . --target {} --report-json ./.uto/reports/last-run.json\n\n# Summarize report\nuto report --project .\n\n# Generate HTML report\nuto report --project . --html\n\n# Run template integration tests directly\ncargo test\n```\n\n## Simple Session API\n\nGenerated tests use `uto-test` directly so setup/session code stays concise while logs remain explicit:\n\n```rust\nlet session = uto_test::startNewSession(\"chrome\").await?;\nlet mobile = uto_test::startNewSessionWithArg(\"android\", 16).await?;\n```\n\nRust-style equivalents are also available:\n\n```rust\nlet session = uto_test::start_new_session(\"chrome\").await?;\nlet mobile = uto_test::start_new_session_with_hint(\"android\", 16).await?;\n```\n\n## Files\n\n- `uto.json`: project config\n- `src/bin/uto_project_runner.rs`: local project runner used by `uto run`\n- `tests/web_example.rs`: web example test using `uto-test`\n- `tests/mobile_example.rs`: mobile example test using `uto-test`\n- `.uto/reports/`: structured run reports\n",
        config.project_name, config.default_target
    )
}

pub fn cargo_toml(project_name: &str, uto_root: &Path) -> String {
    format!(
        "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\n\n[dependencies]\nuto-test = {{ path = \"{}\" }}\nuto-runner = {{ path = \"{}\" }}\nuto-reporter = {{ path = \"{}\" }}\nuto-logger = {{ path = \"{}\" }}\nuto-core = {{ path = \"{}\" }}\ntokio = {{ version = \"1\", features = [\"full\"] }}\nlog = \"0.4\"\nserde_json = \"1\"\nwhich = \"7\"\n\n",
        project_name,
        uto_root.join("uto-test").display(),
        uto_root.join("uto-runner").display(),
        uto_root.join("uto-reporter").display(),
        uto_root.join("uto-logger").display(),
        uto_root.join("uto-core").display()
    )
}

pub fn project_runner_rs() -> String {
    r##"use serde_json::json;
use uto_core::{
    driver,
    error::UtoError,
    env::{
        mobile_setup::{prepare_mobile_environment, MobileSetupOptions},
        platform::find_chrome_version,
        provisioning::find_or_provision_chromedriver,
    },
    session::{
        mobile::{MobileCapabilities, MobileSession},
        web::WebSession,
        UtoSession,
    },
};
use uto_reporter::Report;
use uto_runner::{CliOptions, RunMode};

#[tokio::main]
async fn main() {
    let _ = uto_logger::init("generated-runner");

    let options = CliOptions::from_env();
    let mut report = Report::new(
        options.report_json,
        options.report_file.clone(),
        options.mode.as_str(),
    );

    let result = match options.mode {
        RunMode::Web => run_web(&mut report).await,
        RunMode::Mobile => run_mobile(&mut report).await,
    };

    match &result {
        Ok(_) => report.finish("passed", None),
        Err(e) => report.finish("failed", Some(e.to_string())),
    }

    report.emit();

    if let Err(e) = result {
        eprintln!("Runner failed: {e}");
        std::process::exit(1);
    }
}

async fn run_web(report: &mut Report) -> uto_core::error::UtoResult<()> {
    let chrome_version = find_chrome_version()?;
    report.event("env.chrome_discovery", "ok", json!({ "chrome_version": chrome_version }));

    let chromedriver = find_or_provision_chromedriver(&chrome_version).await?;
    report.event("env.chromedriver_provision", "ok", json!({ "path": chromedriver.display().to_string() }));

    let driver = driver::start_chromedriver(&chromedriver).await?;
    report.event("driver.chromedriver_start", "ok", json!({ "url": driver.url, "port": driver.port }));

    let mut run_result = Ok(());
    match WebSession::new(&driver.url).await {
        Ok(session) => {
            report.event("session.web_create", "ok", json!({ "driver_url": driver.url }));
            let action = web_actions(&session, report).await;
            if let Err(e) = action {
                run_result = Err(e);
            }
            let _ = Box::new(session).close().await;
        }
        Err(e) => {
            report.event("session.web_create", "failed", json!({ "error": e.to_string() }));
            run_result = Err(e);
        }
    }

    let _ = driver.stop();
    report.event("driver.chromedriver_stop", "ok", json!({}));
    run_result
}

async fn web_actions(session: &WebSession, report: &mut Report) -> uto_core::error::UtoResult<()> {
    session.goto("https://example.com").await?;
    report.event("session.goto", "ok", json!({ "target": "https://example.com" }));

    let title = session.title().await?;
    report.event("assert.title", "ok", json!({ "title": title }));

    Ok(())
}

async fn run_mobile(report: &mut Report) -> uto_core::error::UtoResult<()> {
    let setup = prepare_mobile_environment(&MobileSetupOptions {
        require_online_device: true,
        ..MobileSetupOptions::default()
    })?;

    report.event(
        "env.mobile_setup",
        "ok",
        json!({
            "android_sdk_root": setup.android_sdk.root.display().to_string(),
            "appium_path": setup.appium_path.display().to_string(),
            "device_serial": setup.device_serial
        }),
    );

    let appium = driver::start_appium(&setup.appium_path).await?;
    report.event("driver.appium_start", "ok", json!({ "url": appium.url, "port": appium.port }));

    let caps = MobileCapabilities::android(
        setup
            .device_serial
            .unwrap_or_else(|| "emulator-5554".to_string()),
    );

    let mut run_result = Ok(());
    match MobileSession::new(&appium.url, caps).await {
        Ok(session) => {
            report.event("session.mobile_create", "ok", json!({ "driver_url": appium.url }));
            let action = mobile_actions(&session, report).await;
            if let Err(e) = action {
                run_result = Err(e);
            }
            let _ = Box::new(session).close().await;
        }
        Err(e) => {
            report.event("session.mobile_create", "failed", json!({ "error": e.to_string() }));
            run_result = Err(e);
        }
    }

    let _ = appium.stop();
    report.event("driver.appium_stop", "ok", json!({}));
    run_result
}

async fn mobile_actions(session: &MobileSession, report: &mut Report) -> uto_core::error::UtoResult<()> {
    session.launch_activity("com.android.settings", ".Settings").await?;
    report.event("session.launch_activity", "ok", json!({ "activity": "Settings" }));

    for label in ["Search settings", "Search", "Rechercher", "Buscar", "Suchen"] {
        match session.select(label).await {
            Ok(_) => {
                report.event("intent.select", "ok", json!({ "intent": label, "strategy": "label" }));
                return Ok(());
            }
            Err(e) => {
                report.event("intent.select", "failed", json!({ "intent": label, "error": e.to_string() }));
            }
        }
    }

    Err(UtoError::SessionCommandFailed(
        "Mobile template objective failed: no search label resolved".to_string(),
    ))
}
"##
    .to_string()
}

pub fn web_test_example() -> String {
    r##"#[tokio::test]
async fn web_example_navigates_example_dot_com_or_skips() {
    let session = match uto_test::startNewSession("chrome").await {
        Ok(session) => session,
        Err(_) => {
            println!("Skipping web example: web session could not be created");
            return;
        }
    };

    session.goto("https://example.com").await.expect("goto");
    let title = session.title().await.expect("title");
    assert!(!title.is_empty());

    session.close().await.expect("close");
}
"##
    .to_string()
}

pub fn mobile_test_example() -> String {
    r##"#[tokio::test]
async fn mobile_example_creates_session_or_skips() {
    let session = match uto_test::startNewSessionWithArg("android", 16).await {
        Ok(session) => session,
        Err(err) => {
            println!("Skipping mobile example: mobile session could not be created: {err}");
            return;
        }
    };

    session.close().await.expect("close mobile session");
}
"##
    .to_string()
}
