//! Generated project templates and configuration.

use crate::config::UtoProjectConfig;
use std::path::Path;

pub fn project_readme(config: &UtoProjectConfig) -> String {
    format!(
        "# {}\n\nGenerated by `uto init`.\n\nThis is a standalone UTO test project template with example tests and a local runner.\n\n## Quick Start\n\n```sh\n# Run default target\nuto run --project .\n\n# Run explicit target\nuto run --project . --target {} --report-json ./.uto/reports/last-run.json\n\n# Summarize report\nuto report --project .\n\n# Generate HTML report\nuto report --project . --html\n\n# Run template integration tests directly\ncargo test\n```\n\n## Suite API\n\nThe generated runner uses the UTO Suite API so one file can define multiple named test cases:\n\n```rust\nlet code = uto_test::Suite::new(uto_runner::CliOptions::from_env())\n    .test(\"web: page title is non-empty\", web_title_test)\n    .test(\"web: inline form assertion\", web_form_test)\n    .run()\n    .await;\n```\n\nEach test runs in an isolated managed session and emits `uto-suite/v1` JSON plus native HTML reports.\n\n## Files\n\n- `uto.json`: project config\n- `src/bin/uto_project_runner.rs`: local project runner used by `uto run`\n- `tests/web_example.rs`: web example test using `uto-test`\n- `tests/mobile_example.rs`: mobile example test using `uto-test`\n- `.uto/reports/`: structured run reports\n",
        config.project_name, config.default_target
    )
}

pub fn cargo_toml(project_name: &str, uto_root: &Path) -> String {
    format!(
        "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\n\n[dependencies]\nuto-test = {{ path = \"{}\" }}\nuto-runner = {{ path = \"{}\" }}\nuto-reporter = {{ path = \"{}\" }}\nuto-logger = {{ path = \"{}\" }}\nuto-core = {{ path = \"{}\" }}\ntokio = {{ version = \"1\", features = [\"full\"] }}\nlog = \"0.4\"\nserde_json = \"1\"\nwhich = \"7\"\n\n",
        project_name,
        uto_root.join("uto-test").display(),
        uto_root.join("uto-runner").display(),
        uto_root.join("uto-reporter").display(),
        uto_root.join("uto-logger").display(),
        uto_root.join("uto-core").display()
    )
}

pub fn project_runner_rs() -> String {
    r##"use uto_core::error::{UtoError, UtoResult};
use uto_runner::{CliOptions, RunMode};
use uto_test::{ManagedSession, Suite};

#[tokio::main]
async fn main() {
    let _ = uto_logger::init("generated-runner");

    let options = CliOptions::from_env();
    let mode = options.mode;

    let suite = Suite::new(options);
    let exit_code = match mode {
        RunMode::Web => suite
            .test("web: page title is non-empty", web_title_test)
            .test("web: inline form assertion", web_form_test)
            .run()
            .await,
        RunMode::Mobile => suite
            .test("mobile: settings launches", mobile_launch_settings_test)
            .test("mobile: find search intent", mobile_search_intent_test)
            .run()
            .await,
    };

    std::process::exit(exit_code);
}

async fn web_title_test(session: ManagedSession) -> UtoResult<()> {
    session.goto("https://example.com").await?;
    let title = session.title().await?;
    if title.is_empty() {
        return Err(UtoError::SessionCommandFailed(
            "title assertion failed: expected non-empty title".to_string(),
        ));
    }
    session.close().await
}

async fn web_form_test(session: ManagedSession) -> UtoResult<()> {
    session
        .goto(concat!(
            "data:text/html,",
            "<html><body>",
            "<input id='e' aria-label='Email' type='text'/>",
            "<button id='s' aria-label='Submit' ",
            "onclick=\"document.getElementById('o').textContent=",
            "document.getElementById('e').value\">Submit</button>",
            "<p id='o'>-</p>",
            "</body></html>"
        ))
        .await?;

    session.fill_intent("Email", "template@uto.dev").await?;
    session.click_intent("Submit").await?;

    let out = session.find_element("#o").await?;
    let text = session.get_text(&out).await?;
    if text != "template@uto.dev" {
        return Err(UtoError::SessionCommandFailed(format!(
            "form assertion failed: expected 'template@uto.dev', got '{text}'"
        )));
    }

    session.close().await
}

async fn mobile_launch_settings_test(session: ManagedSession) -> UtoResult<()> {
    session
        .launch_android_activity("com.android.settings", ".Settings")
        .await?;
    session.close().await
}

async fn mobile_search_intent_test(session: ManagedSession) -> UtoResult<()> {
    session
        .launch_android_activity("com.android.settings", ".Settings")
        .await?;

    for label in ["Search settings", "Search", "Rechercher", "Buscar", "Suchen"] {
        if session.select(label).await.is_ok() {
            return session.close().await;
        }
    }

    let _ = session.close().await;
    Err(UtoError::SessionCommandFailed(
        "mobile assertion failed: no search intent resolved".to_string(),
    ))
}
"##
    .to_string()
}

pub fn web_test_example() -> String {
    r##"#[tokio::test]
async fn web_example_navigates_example_dot_com_or_skips() {
    let session = match uto_test::startNewSession("chrome").await {
        Ok(session) => session,
        Err(_) => {
            println!("Skipping web example: web session could not be created");
            return;
        }
    };

    session.goto("https://example.com").await.expect("goto");
    let title = session.title().await.expect("title");
    assert!(!title.is_empty());

    session.close().await.expect("close");
}
"##
    .to_string()
}

pub fn mobile_test_example() -> String {
    r##"#[tokio::test]
async fn mobile_example_creates_session_or_skips() {
    let session = match uto_test::startNewSessionWithArg("android", 16).await {
        Ok(session) => session,
        Err(err) => {
            println!("Skipping mobile example: mobile session could not be created: {err}");
            return;
        }
    };

    session.close().await.expect("close mobile session");
}
"##
    .to_string()
}
