#!/usr/bin/env sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
COPILOT_INSTRUCTIONS="$ROOT_DIR/.github/copilot-instructions.md"
COPILOT_PROMPTS_DIR="$ROOT_DIR/.github/prompts"
COPILOT_AGENT="$ROOT_DIR/.github/agents/uto-architect.agent.md"

GEMINI_DIR="$ROOT_DIR/.gemini"
GEMINI_INSTRUCTIONS="$GEMINI_DIR/instructions.md"
GEMINI_PROMPTS="$GEMINI_DIR/prompts.md"
GEMINI_AGENT="$GEMINI_DIR/agent.json"

MODE="${1:-sync}"
if [ "$MODE" != "sync" ] && [ "$MODE" != "--check" ]; then
  echo "Usage: $0 [sync|--check]" >&2
  exit 2
fi

json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

frontmatter_value() {
  file="$1"
  key="$2"
  awk -v key="$key" '
    NR == 1 && $0 == "---" { in_fm = 1; next }
    in_fm && $0 == "---" { exit }
    in_fm {
      if ($0 ~ ("^" key ":")) {
        sub("^" key ":[[:space:]]*", "")
        gsub(/^"|"$/, "")
        print
        exit
      }
    }
  ' "$file"
}

frontmatter_body() {
  file="$1"
  awk '
    /^---$/ { sep++; next }
    sep >= 2 { print }
  ' "$file"
}

render_gemini_instructions() {
  cat <<'EOF'
# UTO Project - Gemini Agent Instructions

> AUTO-GENERATED from `.github/copilot-instructions.md`.
> Do not edit this file manually. Run `./scripts/sync_ai_configs.sh`.

EOF
  cat "$COPILOT_INSTRUCTIONS"
}

render_gemini_prompts() {
  cat <<'EOF'
# UTO Project - Gemini Agent Prompts

> AUTO-GENERATED from `.github/prompts/*.prompt.md`.
> Do not edit this file manually. Run `./scripts/sync_ai_configs.sh`.

## Prompt Catalog

EOF

  for prompt_file in "$COPILOT_PROMPTS_DIR"/*.prompt.md; do
    [ -f "$prompt_file" ] || continue
    prompt_name=$(frontmatter_value "$prompt_file" "name")
    prompt_desc=$(frontmatter_value "$prompt_file" "description")
    printf -- "- **%s**: %s\n" "$prompt_name" "$prompt_desc"
  done

  echo

  for prompt_file in "$COPILOT_PROMPTS_DIR"/*.prompt.md; do
    [ -f "$prompt_file" ] || continue
    prompt_name=$(frontmatter_value "$prompt_file" "name")
    prompt_desc=$(frontmatter_value "$prompt_file" "description")

    printf "## %s\n\n" "$prompt_name"
    if [ -n "$prompt_desc" ]; then
      printf "%s\n\n" "$prompt_desc"
    fi
    frontmatter_body "$prompt_file"
    echo
  done
}

render_gemini_agent_json() {
  agent_name=$(frontmatter_value "$COPILOT_AGENT" "name")
  agent_desc=$(frontmatter_value "$COPILOT_AGENT" "description")
  agent_hint=$(frontmatter_value "$COPILOT_AGENT" "argument-hint")

  body_intro=$(awk '
    /^---$/ { sep++; next }
    sep >= 2 && NF { print; exit }
  ' "$COPILOT_AGENT")

  if [ -z "$agent_name" ]; then
    agent_name="uto-architect"
  fi

  identity=$(json_escape "$body_intro")
  role=$(json_escape "$agent_desc")
  personality=$(json_escape "$agent_hint")

  cat <<EOF
{
  "name": "$(json_escape "$agent_name")",
  "identity": "$identity",
  "role": "$role",
  "personality": "$personality",
  "source": ".github/agents/uto-architect.agent.md"
}
EOF
}

TMP_DIR=$(mktemp -d)
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

mkdir -p "$TMP_DIR"
render_gemini_instructions > "$TMP_DIR/instructions.md"
render_gemini_prompts > "$TMP_DIR/prompts.md"
render_gemini_agent_json > "$TMP_DIR/agent.json"

check_one() {
  target="$1"
  generated="$2"
  if [ ! -f "$target" ] || ! cmp -s "$target" "$generated"; then
    echo "Out of sync: $target" >&2
    return 1
  fi
  return 0
}

if [ "$MODE" = "--check" ]; then
  status=0
  check_one "$GEMINI_INSTRUCTIONS" "$TMP_DIR/instructions.md" || status=1
  check_one "$GEMINI_PROMPTS" "$TMP_DIR/prompts.md" || status=1
  check_one "$GEMINI_AGENT" "$TMP_DIR/agent.json" || status=1
  if [ "$status" -ne 0 ]; then
    echo "Run ./scripts/sync_ai_configs.sh to regenerate .gemini files." >&2
  fi
  exit "$status"
fi

mkdir -p "$GEMINI_DIR"
cp "$TMP_DIR/instructions.md" "$GEMINI_INSTRUCTIONS"
cp "$TMP_DIR/prompts.md" "$GEMINI_PROMPTS"
cp "$TMP_DIR/agent.json" "$GEMINI_AGENT"

echo "Synced Gemini config from GitHub Copilot config."